CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(36) PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  password_hash VARCHAR(100) NOT NULL,
  created TIMESTAMP WITH TIME ZONE NOT NULL,
  modified TIMESTAMP WITH TIME ZONE NOT NULL,
  last_login TIMESTAMP WITH TIME ZONE NOT NULL,
  token VARCHAR(1024),
  is_active BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS user_phones (
  id IDENTITY PRIMARY KEY,
  user_id VARCHAR(36) NOT NULL,
  number VARCHAR(20) NOT NULL,
  city_code VARCHAR(10) NOT NULL,
  country_code VARCHAR(10) NOT NULL,
  CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
